### ISSUE TITLE
Not support angular 1.6.x

### ISSUE THREAD

**Issue by matinfo** [nkovacic/angular-touchspin#11]
I noticed that the *options="optionsVariable"* passed to the directive not more work with Angular JS 1.6.x

**Comment by nkovacic** [comment]
Could you please create a plunkr, so I can see what exactly is not working?

**Comment by matinfo** [comment]
Here a CodePen: http://codepen.io/matinfo/pen/yaJRLy/

The touchspin is no more setup based of the *options* passed to the directive.

Try to change in settings the angular.js file call to 1.5.10 in place of 1.6.0 and now you see the vertical example working + options provided.

**Comment by nkovacic** [comment]
Looks like it has something to do with the new angular 1.6 $onInit function as described [here](http://stackoverflow.com/questions/41116962/directives-passing-parameter-undefined-while-updating-1-5-x-to-1-6-angular)
Fix for this will probably take a while because I havent update any of my projects to 1.6.

**Comment by nkovacic** [comment]
Fixed in [1.4.2](https://github.com/nkovacic/angular-touchspin/releases/tag/1.4.2)

**Comment by matinfo** [comment]
https://toddmotto.com/angular-1-6-is-here#component-and-oninit
